// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRS9sdT9imFEW7BRGUhquhilOvY5xkfDQ',
    appId: '1:125457112288:web:8e0930b892d286c14b0485',
    messagingSenderId: '125457112288',
    projectId: 'agroguru-2850c',
    authDomain: 'agroguru-2850c.firebaseapp.com',
    storageBucket: 'agroguru-2850c.appspot.com',
    measurementId: 'G-ZBR6613TNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkh8v3UvblnfxLNltTy7CCBcCGKTK1Sw',
    appId: '1:125457112288:android:cbebb8a21997de3d4b0485',
    messagingSenderId: '125457112288',
    projectId: 'agroguru-2850c',
    storageBucket: 'agroguru-2850c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-nCljUL_P13FdAJRS5eASJd7_RrXZHc',
    appId: '1:125457112288:ios:17f0aed53f332a034b0485',
    messagingSenderId: '125457112288',
    projectId: 'agroguru-2850c',
    storageBucket: 'agroguru-2850c.appspot.com',
    androidClientId: '125457112288-eikfbsu7cp0et4us2tib90s1ht35cn5e.apps.googleusercontent.com',
    iosClientId: '125457112288-k2jkgbgak60qrro8ih6rpnae30vsnhl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroguru',
  );
}
