// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxkjBLQdZCwXK3OI3Qn9meFyUAAqIYMU',
    appId: '1:301985586495:web:7ffd8bffa99a9d68af478a',
    messagingSenderId: '301985586495',
    projectId: 'agroguru-65f47',
    authDomain: 'agroguru-65f47.firebaseapp.com',
    storageBucket: 'agroguru-65f47.appspot.com',
    measurementId: 'G-0BT6PFM2NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNlp30cxR83hD7OK2fNVTvRSxBomsWAHY',
    appId: '1:301985586495:android:41d8487b786bfbf7af478a',
    messagingSenderId: '301985586495',
    projectId: 'agroguru-65f47',
    storageBucket: 'agroguru-65f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCscTEtNHKQu44IjWYfvSc-HRDzwtuDr2w',
    appId: '1:301985586495:ios:6afc1e804289ceccaf478a',
    messagingSenderId: '301985586495',
    projectId: 'agroguru-65f47',
    storageBucket: 'agroguru-65f47.appspot.com',
    iosBundleId: 'com.example.agroguru',
  );
}
